#!/bin/sh
# Script: nw2
# Opens a new Terminal window

script_dir=$(dirname "$(dirname "$0")")

osascript  <<EOF
tell app "Terminal"
  do script "/usr/bin/env -i HOME=$HOME PATH=/usr/bin:/bin:/usr/sbin:/etc:/usr/lib $script_dir/MacOS/Grass.sh"
end tell
EOF

